_specver: 2
modpack:
  name: The Techmyth Pack
  description: The ultimate forge 1.20.1 kitchen sink pack!

install:
  mcVersion: 1.20.1
  loaderVersion: 47.3.12
  installerUrl: "https://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar"
  installerArguments:
    - "--installServer"
  modpackUrl: https://mediafilez.forgecdn.net/files/5921/712/The+Techmyth+Pack-0.2.0.zip
  modpackFormat: curse

  formatSpecific:
    ignoreProject:
      - 263420  #Xaeros Minimap
      - 317780  #Xaeros Worldmap
      - 232131  #Default Options
      - 231275  #Ding
      - 367706  #FancyMenu
      - 358191  #PackMenu
      - 271740  #ToastControl
      - 431430  #FlickerFix
      - 363363  #Extreme Sound Muffler
      - 394468  #Sodium/Embeddium
      - 986380  #Lighty
      - 844662  #Entity Model Features
      - 568563  #Entity Texture Features
      - 915902  #Euphoria Patches
      - 690971  #SeasonHUD
      - 1089803 #Better Modlist
      - 248787  #appleskin
      - 570544  #eating animation
      - 353051  #Game menu mod option
      - 1023209 #create fuel and water info
      - 858542  #searchables
      - 558905  #embeddium/sodium extras
      - 543661  #stylish effects
      - 272515  #Better Advancements
      - 401648  #BetterF3
      - 482444  #Boat Item View
      - 883502  #Bobby
      - 459701  #Catalogue
      - 60089   #mouse tweaks
      - 251407  #client tweaks
      - 250398  #controlling
      - 936713  #emi enchanting
      - 250419  #enchantment descriptions
      - 448233  #entity culling
      - 463155  #Falling Leaves
      - 280294  #FPS Reducer
      - 686911  #ImmediatelyFast
      - 532127  #Legendary Tooltips
      - 676136  #Model Gap Fix
      - 492574  #My Server Is Compatible
      - 441114  #Nekos enchanted books
      - 433760  #Not enough animations
      - 659897  #Flywheel Compat
      - 1130957 #Mekalus
      - 581495  #Oculus
      - 985426  #Particle Core
      - 351441  #Pick up notifier
      - 377109  #Tool Stats

  baseInstallPath:
  additionalFiles: ~
    url: https://media.forgecdn.net/files/2874/966/Morpheus-1.15.2-4.2.46.jar
    destination: mods/Morpheus-1.15.2-4.2.46.jar
    url: https://media.forgecdn.net/files/2876/89/spark-forge.jar
    destination: mods/spark-forge.jar
  checkFolder: true
  installLoader: true
  installPack: true
  spongeBootstrapper: ~
  connectTimeout: 90
  readTimeout: 90



# settings regarding the launching of the pack
launch:
  # specifies the max amount of ram the server is supposed to launch with (Xmx)
  maxRam: 12G
  # specifies the minimal amount of ram the server is supposed to launch with (Xms)
  minRam: 6G
  # specifies whether the server is supposed to auto restart after crash
  autoRestart: false
  javaArgs:
  "-XX:+UseG1GC"
  "-XX:+ParallelRefProcEnabled"
  "-XX:MaxGCPauseMillis=200"
  "-XX:+UnlockExperimentalVMOptions"
  "-XX:+DisableExplicitGC"
  "-XX:+AlwaysPreTouch"
  "-XX:G1NewSizePercent=30"
  "-XX:G1MaxNewSizePercent=40"
  "-XX:G1HeapRegionSize=8M"
  "-XX:G1ReservePercent=20"
  "-XX:G1HeapWastePercent=5"
  "-XX:G1MixedGCCountTarget=4"
  "-XX:InitiatingHeapOccupancyPercent=15"
  "-XX:G1MixedGCLiveThresholdPercent=90"
  "-XX:G1RSetUpdatingPauseTimePercent=5"
  "-XX:SurvivorRatio=32"
  "-XX:+PerfDisableSharedMem"
  "-XX:MaxTenuringThreshold=1"
  "-Dusing.aikars.flags=https://mcflags.emc.gs"
  "-Daikars.new.flags=true"
  spongefix: false
  ramDisk: false
  checkOffline: false
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  forcedJavaPath: ~
  startCommand:
    - "@libraries/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/{{@os@}}_args.txt"
    - "nogui"