#Chance the player's boots will be damaged by an air hop.
#Default Value: 0.15
# Default: 0.15
# Range: 0.0 ~ 1.0
boots_damage_chance = 0.15
#Spawn a small particle cloud at the players feet on every air hop.
#Default Value: true
spawn_particle_cloud = true
#Prevent air hop enchantment from working when the player has 6 or less food points.
#Default Value: true
disable_on_hungry = true
#Take normal fall damage when hitting the ground after air hopping.
#Default Value: false
normal_fall_damage = false
#Air hopping can only be used while falling to prevent gaining too much height.
#Default Value: false
only_when_falling = false
#Play a funny sound effect whenever the player hops in mid-air.
#Default Value: true
play_hopping_sound = true
