["Mekanism Turrets Config"]
	#Entities which will never be targeted by turrets
	blacklistedEntities = ["minecraft:ender_dragon", "minecraft:iron_golem"]
	#Cooldown of the Basic Laser Turret
	# Default: 80
	# Range: > 0
	basicLaserTurretCooldown = 80
	#Damage of the Basic Laser Turret
	# Default: 1.0
	# Range: 0.0 ~ 3.4028234663852886E38
	basicLaserTurretDamage = 1.0
	#Energy Capacity of the Basic Laser Turret
	# Default: 10000
	# Range: > 0
	basicLaserTurretEnergyCapacity = 10000
	#Range of the Basic Laser Turret
	# Default: 15.0
	# Range: 0.0 ~ 1000.0
	basicLaserTurretRange = 15.0
	#Cooldown of the Advanced Laser Turret
	# Default: 65
	# Range: > 0
	advancedLaserTurretCooldown = 65
	#Damage of the Advanced Laser Turret
	# Default: 2.0
	# Range: 0.0 ~ 2.147483647E9
	advancedLaserTurretDamage = 2.0
	#Energy Capacity of the Advanced Laser Turret
	# Default: 40000
	# Range: > 0
	advancedLaserTurretEnergyCapacity = 40000
	#Range of the Advanced Laser Turret
	# Default: 20.0
	# Range: 0.0 ~ 1000.0
	advancedLaserTurretRange = 20.0
	#Cooldown of the Elite Laser Turret
	# Default: 50
	# Range: > 0
	eliteLaserTurretCooldown = 50
	#Damage of the Elite Laser Turret
	# Default: 3.0
	# Range: 0.0 ~ 2.147483647E9
	eliteLaserTurretDamage = 3.0
	#Energy Capacity of the Elite Laser Turret
	# Default: 90000
	# Range: > 0
	eliteLaserTurretEnergyCapacity = 90000
	#Range of the Elite Laser Turret
	# Default: 25.0
	# Range: 0.0 ~ 1000.0
	eliteLaserTurretRange = 25.0
	#Cooldown of the Ultimate Laser Turret
	# Default: 35
	# Range: > 0
	ultimateLaserTurretCooldown = 35
	#Damage of the Ultimate Laser Turret
	# Default: 4.0
	# Range: 0.0 ~ 2.147483647E9
	ultimateLaserTurretDamage = 4.0
	#Energy Capacity of the Ultimate Laser Turret
	# Default: 160000
	# Range: > 0
	ultimateLaserTurretEnergyCapacity = 160000
	#Range of the Ultimate Laser Turret
	# Default: 30.0
	# Range: 0.0 ~ 1000.0
	ultimateLaserTurretRange = 30.0
