[general]
giveJournal = false
holdToCast = true
doMinigame = false
showUnread = true
showToasts = true
minigameDifficulty = 1.0
rodDurabilityMultiplier = 1.0
defaultLineColor = true
hideUnknownFishNames = true
baseCrateRarity = 20
[worldgen]
disableFishingBoat = false
